# Linux tests makefile for Glide3
#
#  Copyright (c) 2002 - Borca Daniel
#  Email : dborca@users.sourceforge.net
#  Web   : http://www.geocities.com/dborca
#
# $Header$
#


#
#  Available options:
#
#    Environment variables:
#	DGA=1		Build DGA version (experimental).
#			default = no
#	XPATH		specify X libraries path; needed by DGA.
#			default = /usr/X11/lib
#	CPU		optimize for the given processor.
#			default = pentium
#
#    Targets:
#	<file.exe>	build a specific file
#


.PHONY: all
.SUFFIXES: .c .o .exe
.SECONDARY: tlib.o

FX_GLIDE_HW = h5
TOP = ../../..
CPU ?= pentium
XPATH ?= /usr/X11/lib

CC = gcc
CFLAGS = -Wall -O2 -ffast-math -mcpu=$(CPU)
CFLAGS += -I$(TOP)/$(FX_GLIDE_HW)/glide3/src -I$(TOP)/$(FX_GLIDE_HW)/incsrc
CFLAGS += -I$(TOP)/swlibs/fxmisc
CFLAGS += -DH3
CFLAGS += -DFX_GLIDE_NAPALM=1

LDFLAGS = -s -L$(TOP)/$(FX_GLIDE_HW)/lib

LDLIBS = -lglide3
ifeq ($(DGA),1)
LDFLAGS += -L$(XPATH)
LDLIBS += -lX11 -lXext -lXxf86dga
endif
LDLIBS += -lm

.c.o:
	$(CC) -o $@ $(CFLAGS) -c $<
%.exe: tlib.o %.o
	$(CC) -o $@ $(LDFLAGS) $^ $(LDLIBS)

all:
	$(error Must specify <filename.exe> to build)
