
CFLAGS = -I. -I/usr/include/glide

SRCS = $(wildcard test*.c)
OBJS = $(SRCS:.c=.o)
EXECS = $(basename $(SRCS))
LIB_OBJS = tlib.o

all: $(EXECS)

clean:
	rm $(EXECS) *.o

$(EXECS): $(OBJS) $(LIB_OBJS)
	$(CC) -o $@ $@.o $(LIB_OBJS) -lglide3 -lm
