#
# Copyright (c) 1995, 3Dfx Interactive, Inc.
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of 3Dfx Interactive, Inc.;
# the contents of this file may not be disclosed to third parties, copied or
# duplicated in any form, in whole or in part, without the prior written
# permission of 3Dfx Interactive, Inc.
#
# RESTRICTED RIGHTS LEGEND:
# Use, duplication or disclosure by the Government is subject to restrictions
# as set forth in subdivision (c)(1)(ii) of the Rights in Technical Data
# and Computer Software clause at DFARS 252.227-7013, and/or in similar or
# successor clauses in the FAR, DOD or NASA FAR Supplement. Unpublished  -
# rights reserved under the Copyright Laws of the United States.
#


LDIRT= $(PROGRAMS)

GLIDE_ROOT	= $(BUILD_ROOT)/$(FX_GLIDE_HW)

LIBOBJS = tlib.o plib.o

GLIDELIB	= -L$(GLIDE_ROOT)/lib -lglide

LLDLIBS = $(LIBOBJS) $(GLIDELIB)

PRIVATE_HEADERS = tlib.h tlib.c plib.h plib.c tldata.inc

CFILES   = display.c \
	   test00.c \
           test01.c \
           test02.c \
           test03.c \
           test04.c \
           test05.c \
           test06.c \
           test07.c \
           test08.c \
           test09.c \
           test10.c \
           test11.c \
           test12.c \
           test13.c \
           test14.c \
           test15.c \
           test16.c \
           test17.c \
           test18.c \
           test19.c \
           test20.c \
           test21.c \
           test22.c \
           test23.c \
           test24.c \
           test25.c \
           test26.c \
	   test27.c \
           test28.c \
           test29.c \
	   qatest00.c \
	   qatest01.c \
	   h3dtst01.c \
	   h3dtst02.c

PROGRAMS = $(CFILES:.c=)

DATAFILES = alpha.3df decal1.3df lava.3df light.3df matt1.3df miro.3df \
            argb1555.3df argb4444.3df argb8332.3df argb8888.3df \
            ayiq.3df yiq.3df p8.3df ap88.3df rgb332.3df rgb565.3df 

include $(BUILD_ROOT_SWLIBS)/include/make/3dfx.mak


$(PROGRAMS):  $(LIBOBJS)
