# Win32 tests makefile for Glide2
# This makefile MUST be processed by GNU make!!!
#
#  Copyright (c) 2004 - Borca Daniel
#  Email : dborca@users.sourceforge.net
#  Web   : http://www.geocities.com/dborca
#

#
#  Available options:
#
#    Environment variables:
#	FX_GLIDE_HW	build for the given ASIC (sst1, sst96).
#			default = sst1
#	CPU		optimize for the given processor.
#			default = 6
#
#    Targets:
#	<file.exe>	build a specific file
#

.PHONY: all
.SUFFIXES: .c .obj .exe
.SECONDARY: tlib.obj plib.obj

FX_GLIDE_HW ?= sst1
ifeq ($(FX_GLIDE_HW),sst1)
HWDEF = -DSST1
else
ifeq ($(FX_GLIDE_HW),sst96)
HWDEF = -DSST96
endif
endif

override FX_HW_BASE = sst1
TOP = ../../..
CPU ?= 6

CC = cl
CFLAGS = -nologo -W3 -WX -D__MSC__=1 -DNDEBUG -G$(CPU) -O2 -MT
CFLAGS += -I$(TOP)/$(FX_HW_BASE)/glide/src -I$(TOP)/$(FX_HW_BASE)/incsrc -I$(TOP)/$(FX_HW_BASE)/init
CFLAGS += -I$(TOP)/swlibs/fxmisc
CFLAGS += -D__WIN32__ $(HWDEF)

LD = link
LDFLAGS = -nologo -opt:WIN98 -machine:IX86
LDLIBS = user32.lib gdi32.lib $(TOP)/$(FX_HW_BASE)/lib/$(FX_GLIDE_HW)/glide2x.lib

.c.obj:
	$(CC) -Fo$@ $(CFLAGS) -c $<
%.exe: tlib.obj %.obj
	$(LD) -out:$@ $(LDFLAGS) $^ $(LDLIBS)

all:
	$(error Must specify <filename.exe> to build)

qatest00.exe: tlib.obj plib.obj qatest00.obj
	$(LD) -out:$@ $(LDFLAGS) $^ $(LDLIBS)
