# Linux tests makefile for Glide2
#
#  Copyright (c) 2002 - Borca Daniel
#  Email : dborca@users.sourceforge.net
#  Web   : http://www.geocities.com/dborca
#

#
#  Available options:
#
#    Environment variables:
#	FX_GLIDE_HW	build for the given ASIC (sst1, sst96).
#			default = sst1
#	CPU		optimize for the given processor.
#			default = pentium
#	XPATH		specify X11 path; needed for sst96.
#			default = /usr/X11R6 (sst96 only)
#	X11LIBS		X libraries path; default = $(XPATH)/lib
#
#    Targets:
#	<file.exe>	build a specific file
#


.PHONY: all clean
.SUFFIXES: .c .o .exe
.SECONDARY: tlib.o plib.o linutil.o

FX_GLIDE_HW ?= sst1
XPATH ?= /usr/X11R6
X11LIBS ?= $(XPATH)/lib
ifeq ($(FX_GLIDE_HW),sst1)
HWDEF = -DSST1
endif
ifeq ($(FX_GLIDE_HW),sst96)
HWDEF = -DSST96
endif

override FX_HW_BASE = sst1
TOP = ../../..
CPU ?= pentium

CC = gcc
CFLAGS = -Wall -O2 -ffast-math -mtune=$(CPU)
CFLAGS += -I$(TOP)/$(FX_HW_BASE)/glide/src -I$(TOP)/$(FX_HW_BASE)/incsrc -I$(TOP)/$(FX_HW_BASE)/init
CFLAGS += -I$(TOP)/swlibs/fxmisc
CFLAGS += $(HWDEF)

LDFLAGS = -s -L$(TOP)/$(FX_HW_BASE)/lib/$(FX_GLIDE_HW)

LDLIBS = -lglide2x
ifeq ($(FX_GLIDE_HW),sst96)
LDLIBS += -L$(X11LIBS) -lXxf86dga -lXxf86rush -lXxf86vm
endif
LDLIBS += -lm

.c.o:
	$(CC) -o $@ $(CFLAGS) -c $<
%.exe: linutil.o tlib.o %.o
	$(CC) -o $@ $(LDFLAGS) $^ $(LDLIBS)

all:
	$(error Must specify <filename.exe> to build)

linutil.o: $(TOP)/swlibs/fxmisc/linutil.c
	$(CC) -o $@ $(CFLAGS) -c $<

qatest00.exe: linutil.o tlib.o plib.o  qatest00.o
	$(CC) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f *.o
	rm -f *.exe
