#!/bin/csh -f
#
# $Log$
# Revision 1.1.1.1  2000/03/16 20:38:24  bwhite
# Imported CSIM sources
#
# Revision 1.5  1996/11/01 18:49:35  psmith
# added "-all" flag which echoes all the supported architecture types
#
# Revision 1.4  1996/10/30 20:04:57  psmith
# modified to conform to new /home/tools directory structure
#
# Revision 1.3  1996/09/03 18:06:19  psmith
# revised architecture names to: solaris, sunos, hpux
#
#

# if '-all' flag, return all supported architecture types

if ( $#argv >= 1 ) then
        if ( $1 == "-all" ) then
                echo "hpux sunos solaris linux"
                exit
        endif
endif

# determine and return machine architecture type

set a = `/bin/uname -s`
switch ($a)
case "HP-UX":
    echo "hpux"
    exit
case "SunOS":
    set b = `/bin/uname -r | /usr/bin/cut -c1`
    if ($b > 4) then
        echo "solaris"
        exit
    else
        echo "sunos"
        exit
    endif
case "Linux":
    echo "Linux"
	exit
default:
    echo "unknown"
	exit
endsw
